version: '2'
services:
  postgres:
    image: postgres:11
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=hamlet"
      - "POSTGRES_PASSWORD=hamlet"

  redis:
    image: redis
    command: redis-server --appendonly yes

  app:
    image: hamlet:local
    build:
      context: .
      args:
        DJANGO_ENV: development
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - redis:redis
      - postgres:postgres
    env_file:
      - .env
    environment:
      - DEBUG=true
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}

  worker:
    image: hamlet:local
    command: bash ./start_worker.sh
    volumes:
      - ./:/usr/src/app
    links:
      - redis:redis
      - postgres:postgres
    env_file:
      - .env
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}

  # Flower is a celery monitoring tool
  flower:
    image: hamlet:local
    command: celery -A hamlet flower --port=5555
    volumes:
      - ./:/usr/src/app
    links:
      - redis:redis
      - postgres:postgres
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}

