version: '2'
services:
  postgres:
    image: postgres:9.4
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=hamlet"
      - "POSTGRES_PASSWORD=hamlet"

  redis:
    image: redis:5.0.3-stretch
    command: redis-server --appendonly yes

  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - redis:redis
      - postgres:postgres
    env_file:
      - .env

  worker:
    build:
      context: .
    command: bash ./start_worker.sh
    volumes:
      - ./:/usr/src/app
    links:
      - redis:redis
      - postgres:postgres
    env_file:
      - .env
