# Generated by Django 2.2.1 on 2019-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsetexport',
            name='csv',
            field=models.FileField(null=True, upload_to='subject_sets/'),
        ),
    ]
