# Generated by Django 2.2.1 on 2019-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_subjectsetexport_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField()),
                ('status', models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Complete'), ('f', 'Failed')], default='p', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('csv', models.FileField(null=True, upload_to='workflows/')),
            ],
        ),
    ]
