# Generated by Django 2.2.2 on 2019-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_workflowexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediametadata',
            name='celery_task',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='subjectsetexport',
            name='celery_task',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='workflowexport',
            name='celery_task',
            field=models.UUIDField(null=True),
        ),
    ]
