# Generated by Django 2.2.5 on 2019-10-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0004_auto_20190627_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSubjectAssistantExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Complete'), ('f', 'Failed')], default='p', max_length=1)),
                ('celery_task', models.UUIDField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject_set_id', models.IntegerField()),
                ('csv', models.FileField(null=True, upload_to='ml_subject_assistant/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
