# Generated by Django 2.2.5 on 2019-10-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_mlsubjectassistantexport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlsubjectassistantexport',
            old_name='csv',
            new_name='json',
        ),
    ]
