# Generated by Django 2.2.6 on 2019-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0006_auto_20191011_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlsubjectassistantexport',
            name='azure_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mlsubjectassistantexport',
            name='ml_task_id',
            field=models.IntegerField(null=True),
        ),
    ]
