# Generated by Django 2.2.14 on 2020-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0007_auto_20191101_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlsubjectassistantexport',
            name='ml_task_id',
        ),
        migrations.AddField(
            model_name='mlsubjectassistantexport',
            name='ml_task_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
