# Generated by Django 2.2.28 on 2022-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0008_auto_20200727_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='KadeSubjectAssistantExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('r', 'Running'), ('c', 'Complete'), ('f', 'Failed')], default='p', max_length=1)),
                ('celery_task', models.UUIDField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject_set_id', models.IntegerField()),
                ('json', models.FileField(null=True, upload_to='ml_subject_assistant/')),
                ('azure_url', models.CharField(max_length=512, null=True)),
                ('service_job_url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
