name: Build PR Branch

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_image:
    name: Build test image
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Test build
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: |
          ghcr.io/zooniverse/hamlet-branch:test
          ghcr.io/zooniverse/hamlet-branch:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
